export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const LOAD_PRODUCT = "LOAD_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const PRODUCT_LOADED = "PRODUCT_LOADED";
